### PR TITLE
Emanuelbutoi branch

### PR DESCRIPTION
**Pull request by EmanuelButoiGit**
added Emanuel Butoi tasks

### CODE REVIEW

**Review by gtlc-ctrl — CHANGES_REQUESTED** [review]
Please add "Reviewed by Liviu-Gabriel Cojocaru"

**Comment by EmanuelButoiGit** [comment]
:)

**Review by EmanuelButoiGit — COMMENTED** [review]
Reviewed by Liviu-Gabriel Cojocaru

**Comment by BogdanBadiu** [comment]
Please add "Reviewed by Bogdan-Vasile Badiu"

**Pull request merged**
